### ISSUE TITLE
Update to latest PHP Markdown script

### ISSUE THREAD

**Issue by dartiss** [dartiss/plugin-readme-parser#22]
The current version causes issues with PHP 8 ([discussed here](https://wordpress.org/support/topic/deprecated-usage-of-curly-braces-throws-fatal-error-under-php-8-0/)).

[Script is now at 1.9.0,](https://michelf.ca/projects/php-markdown/) and appears to resolve all the reported problems.

Will need to update the code to use the new script - not sure if how the interface works has changed, so this may either be a really small job or a massive undertaking. Regardless, it really needs doing.

**Comment by GwynethLlewelyn** [comment]
AFAIK Michel's script has been brought up to current programming standards (no more curly braces where brackets should be used); I'm willing to do a few experiments and send you a PR... it might really be just a drop-in replacement...

**Comment by dartiss** [comment]
Probably related... https://wordpress.org/support/topic/array-and-string-offset-access-syntax-with-curly-braces/

**Comment by morehawes** [comment]
Markdown library updated in [v1.3.12](https://github.com/morehawes/plugin-readme-parser/commit/eef4350655520723670dd4f48490d605e64b6885)

:)

Joe

**Comment by GwynethLlewelyn** [comment]
It works _almost_ flawlessly :)

The "almost" is just because the references I have to screenshots for my plugins (i.e., usually a screengrab of whatever your plugin's dashboard should look like, but it almost always returns with the infamous error:

     Plugin README Parser: Could not find screenshot-1 image file

**Comment by morehawes** [comment]
> The "almost" is just because the references I have to screenshots for my plugins

I don't think this is an issue with the Markdown parser itself - AFAIK "Screenshots" are part of the WordPress readme.txt spec built on top of Markdown.

Cheers,

Joe

**Comment by GwynethLlewelyn** [comment]
Oh I see! I wrongly thought (not having delved deep enough in your code!) that you _did_ account for those WordPress quirks and deviations from "standard" Markdown :)
